import type { Metadata } from "next";
import LegalTemplate, { Section } from "@/components/legal-template";

export const metadata: Metadata = {
  title: "Disclaimer | ResumeForge AI",
  description:
    "ResumeForge AI provides AI-powered assistance only. All generated content must be independently reviewed. We make no guarantees regarding employment outcomes.",
};

const sections = [
  { id: "general-disclaimer", title: "General Disclaimer" },
  { id: "ai-content-limitations", title: "AI Content Limitations" },
  { id: "user-verification", title: "User Verification Responsibility" },
  { id: "no-professional-advice", title: "No Professional Advice" },
  { id: "no-employment-guarantee", title: "No Employment Guarantee" },
  { id: "limitation-of-accuracy", title: "Limitation of Accuracy" },
  { id: "third-party-providers", title: "Third-Party AI Providers" },
  { id: "service-disclaimer", title: "Service Disclaimer" },
];

export default function DisclaimerPage() {
  return (
    <LegalTemplate title="Disclaimer" lastUpdated="June 5, 2026" sections={sections}>
      <Section id="general-disclaimer" title="General Disclaimer">
        <p>
          <strong>
            ResumeForge AI provides AI-powered assistance only and should not be
            considered professional career, legal, recruiting, or employment
            advice.
          </strong>
        </p>
        <p>
          The content, suggestions, analyses, and outputs generated by
          ResumeForge AI are provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis for
          informational and assistance purposes only. We make no representations
          or warranties of any kind, express or implied, regarding the accuracy,
          completeness, reliability, suitability, or availability of any content
          generated through the platform.
        </p>
      </Section>

      <Section id="ai-content-limitations" title="AI Content Limitations">
        <p>
          ResumeForge AI uses artificial intelligence models to generate resume
          content, match scores, and analyses. Users should be aware of the
          following limitations:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            AI-generated content may contain inaccuracies, errors, omissions, or
            information that does not reflect your actual experience or
            qualifications.
          </li>
          <li>
            The AI may produce content that sounds plausible but is factually
            incorrect — commonly referred to as &ldquo;hallucinations.&rdquo;
          </li>
          <li>
            Generated content may not reflect current industry standards,
            terminology, or expectations for your specific field or role.
          </li>
          <li>
            The AI does not have knowledge of specific employer requirements,
            internal hiring practices, or proprietary ATS systems.
          </li>
          <li>
            Match scores and skill gap analyses are estimates based on pattern
            matching and should not be interpreted as definitive assessments.
          </li>
        </ul>
      </Section>

      <Section id="user-verification" title="User Verification Responsibility">
        <p>
          You are solely responsible for reviewing, verifying, and editing all
          content generated by ResumeForge AI before using it in any
          professional, academic, or official capacity. This responsibility
          includes, but is not limited to:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            Verifying the accuracy of all names, dates, company names, job
            titles, and other factual information.
          </li>
          <li>
            Ensuring that technical skills, certifications, and qualifications
            are accurately represented and truthful.
          </li>
          <li>
            Confirming that generated content reflects your authentic
            professional experience and personal voice.
          </li>
          <li>
            Reviewing for any language that may be misleading, exaggerated, or
            inconsistent with your actual background.
          </li>
          <li>
            Customizing the output to ensure it is appropriate for the specific
            role, company, and industry you are targeting.
          </li>
        </ul>
        <p>
          You bear full responsibility for the final content you submit to
          employers, recruiters, or any third party. ResumeForge AI cannot be
          held responsible for how you choose to use or present the generated
          content.
        </p>
      </Section>

      <Section id="no-professional-advice" title="No Professional Advice">
        <p>
          ResumeForge AI does not provide professional services or advice in
          any regulated field, including but not limited to:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>
            <strong>Career Advice:</strong> We do not offer personalized career
            counseling, career path recommendations, or job search strategies.
          </li>
          <li>
            <strong>Legal Advice:</strong> We do not provide legal advice
            regarding employment law, immigration, visa applications,
            non-compete agreements, or any other legal matters.
          </li>
          <li>
            <strong>Recruiting Services:</strong> We are not a recruiting
            agency, headhunter, or employment placement service.
          </li>
          <li>
            <strong>Employment Guarantees:</strong> We do not guarantee
            employment, interviews, or any specific hiring outcomes.
          </li>
          <li>
            <strong>Financial Advice:</strong> We do not provide salary
            negotiation advice or financial counseling.
          </li>
        </ul>
        <p>
          If you require professional advice regarding your job search, career
          decisions, legal matters, or financial considerations, we strongly
          recommend consulting with appropriately qualified professionals,
          including career counselors, attorneys, recruiters, or financial
          advisors.
        </p>
      </Section>

      <Section id="no-employment-guarantee" title="No Employment Guarantee">
        <p>
          <strong>
            ResumeForge AI does not guarantee interviews, job offers,
            employment outcomes, recruiter responses, or ATS compatibility.
          </strong>
        </p>
        <p>
          The effectiveness of any resume or application depends on numerous
          factors beyond the scope of our platform, including:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Your actual qualifications, experience, and skills</li>
          <li>Market conditions and competition for specific roles</li>
          <li>Employer preferences and internal hiring criteria</li>
          <li>Specific ATS implementations and configurations</li>
          <li>Recruiter review processes and human judgment</li>
          <li>Interview performance and overall candidate evaluation</li>
        </ul>
        <p>
          No tool can guarantee success in the job application process. We make
          no representations that use of our platform will result in any
          specific career outcome.
        </p>
      </Section>

      <Section id="limitation-of-accuracy" title="Limitation of Accuracy">
        <p>
          While we strive to provide high-quality AI-generated content, the
      accuracy and quality of outputs depend on several factors:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>The clarity, completeness, and quality of your uploaded resume</li>
          <li>The specificity and detail of the job description you provide</li>
          <li>Current limitations and capabilities of AI language models</li>
          <li>Ambiguities, formatting issues, or OCR errors in uploaded files</li>
          <li>The suitability of AI-generated content for your specific industry or role</li>
        </ul>
        <p>
          We recommend using ResumeForge AI as a supplement to, not a
          replacement for, your own judgment, expertise, and professional input.
          Always review and customize AI-generated content to ensure it
          accurately represents your qualifications and meets your standards.
        </p>
      </Section>

      <Section id="third-party-providers" title="Third-Party AI Providers">
        <p>
          ResumeForge AI relies on third-party AI services, including Google&rsquo;s
          Gemini API, to process and generate content. While we select providers
          with strong security and privacy practices, we cannot guarantee the
          accuracy, reliability, availability, or security of these third-party
          services.
        </p>
        <p>
          We are not responsible for any errors, omissions, inaccuracies, or
          issues arising from the performance, output, or failure of third-party
          AI providers. Users should be aware that AI models are continually
          evolving and may produce different results over time for the same
          inputs.
        </p>
      </Section>

      <Section id="service-disclaimer" title="Service Disclaimer">
        <p>
          To the maximum extent permitted by applicable law, ResumeForge AI
          expressly disclaims all warranties, whether express, implied, or
          statutory, including but not limited to:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Implied warranties of merchantability, fitness for a particular purpose, and non-infringement</li>
          <li>Warranties regarding the accuracy, reliability, or completeness of generated content</li>
          <li>Warranties of uninterrupted or error-free service</li>
          <li>Warranties that the Service will meet your specific requirements or expectations</li>
        </ul>
        <p>
          Your use of ResumeForge AI is at your sole risk. The platform is
          provided free of charge, and you acknowledge that you have not relied
          on any representations or warranties beyond those expressly stated in
          this disclaimer.
        </p>
      </Section>
    </LegalTemplate>
  );
}
